name: CI
run-name: Check ${{ github.ref_name }} by @${{ github.actor }}
on: pull_request
jobs:
  commit-message:
    name: Check commit message format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install commitlint
        run: |
          npm install @commitlint/config-conventional @commitlint/cli
          echo "export default {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Lint commit messages
        run: npx commitlint --from=$(git rev-parse origin/${{ github.base_ref}}) --to=HEAD

  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "*"
      - name: Prepare Linters
        run: npm i
      - name: Run ESLint (*.js)
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          grep -E "\.js$" |
          xargs -r npx eslint
      - name: Run ShellCheck (*.sh)
        if: success() || failure()
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          grep -E "\.sh$" |
          xargs -r shellcheck

  spellcheck:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "*"
      - run: pip install codespell
      # The case sensitivity of codespeller for ignore-words seems to be buggy. See
      # issue tracker. According to the help page it should be case sensitive but
      # only 'allws' makes codespeller ignore 'allWs' in code files.
      - name: Run codespell
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          xargs -r codespell -q 3 --skip="*.po*,*.git/*" --ignore-words .github/ignore-words.txt

  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -q && sudo apt-get install gettext
      - run: bash scripts/build.sh
