name: CI
run-name: Check ${{ github.ref_name }} by @${{ github.actor }}
on: pull_request
jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - name: Prepare Linters
        run: npm i
      - name: Run ESLint (*.js)
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          grep -E "\.js$" |
          xargs -r npx eslint
      - name: Run Prettier
        if: success() || failure()
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          xargs -r npx prettier -c --ignore-unknown
      - name: Run ShellCheck (*.sh)
        if: success() || failure()
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          grep -E "\.sh$" |
          xargs -r shellcheck

  spellcheck:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - run: pip install codespell
      # The case sensitivity of codespeller for ignore-words seems to be buggy. See
      # issue tracker. According to the help page it should be case sensitive but
      # only 'allws' makes codespeller ignore 'allWs' in code files.
      - name: Run codespell
        run: >
          git diff --name-only --diff-filter=ACMTUXB origin/${{ github.base_ref }} HEAD |
          xargs -r codespell -q 3 --skip="*.po*,*.git/*" --ignore-words .github/ignore-words.txt

  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -q && sudo apt-get install gettext
      - run: bash scripts/build.sh
